### ISSUE TITLE
Carrier API must have changed and JSON mappings are no longer accurate.

### ISSUE THREAD

**Issue by gdgeist** [dahlb/carrier_api#1]
**Describe the bug**
The Carrier API has apparently changed and your JSON mapping is no longer valid for a few elements
Specifically:
filter_used -is now a nested JSON response [levels][filter]
IDU and ODU status are now separate  (GET idu_status and Get odu_status)
  airflow_cfm - under idu_status response [iducfm]
  indoor_unit_operational_status - under idu_status response [opstat]
  outdoor_unit_operational_status - under odu_status response [opstat]

there are more and if i get the time will clone and issue a pull request

**To Reproduce**

Review those entities for an active install and they will no longer be available and/or frozen at their last returned value

**Expected behavior**

JSON fields mapped to the updated API

**Screenshots**
![Screenshot 2024-08-16 093847](https://github.com/user-attachments/assets/2c71ba76-7a80-45ca-badb-594bf8cb578b)

**Additional context**
https://openapi.ing.carrier.com/docs

Thanks for this integration - if i can find the time to do the work will see if i can extend it to any other fields.  This is enormously helpful - I used to use the RS485 tap BUT bad things happen if your RS485 tap loses its mind (mine did and bad bad bad)

**Comment by dahlb** [comment]
I see your documentation linked, however that isn't the response format I receive.

I ran the stub just now and still receive "filtrlvl" from the status api

**Comment by dahlb** [comment]
I still see the same results examining the network responses logging in through https://www.myinfinitytouch.carrier.com/account

**Comment by dahlb** [comment]
which firmware are you running? I'm on 
CESR131626-04.56

**Comment by gdgeist** [comment]
CESR131493-14.02.....are you saying my System is old and slow and by extension i am ;)  jk

**Comment by dahlb** [comment]
Thanks for posting your firmware version, I wasn't sure which of us was outdated, but I guess it makes sense that carrier docs would match the outdated version
